[rlbot]
# use this along with launcher = "custom"
# game_path = "legendary"
# "Steam", "Epic", "Custom"
launcher = "steam"
# Should RLBot start the bot processes automatically, or will a separate script start them
auto_start_bots = true

[match]
# What game mode the game should load.
# Accepted values are "Soccer", "Hoops", "Dropshot", "Hockey", "Rumble", "Heatseeker", "Gridiron", "Knockout"
game_mode = "Soccer"
# Which map the game should load into
game_map_upk = "Stadium_P"
# Automatically skip replays after a goal. Also stops match replays from being saved.
skip_replays = false
# Skip the kickoff countdown
start_without_countdown = false
# What should we do if you click run while a match is already in progress?
# "Restart_If_Different", "Restart", "Continue_And_Spawn"
existing_match_behavior = "Restart"
enable_rendering = false
enable_state_setting = true
auto_save_replay = false
# Whether or not to use freeplay instead of an exhibition match
freeplay = false

[mutators]
# "Five_Minutes", "Ten_Minutes", "Twenty_Minutes", "Unlimited"
match_length = "Five_Minutes"
# "Default", "One_Goal", "Three_Goals", "Five_Goals", "Seven Goals", "Unlimited"
max_score = "Default"
# "One", "Two", "Four", "Six"
multi_ball = "One"
# "Unlimited", "Five_Max_First_Score", "Five_Max_Random_Team"
overtime = "Unlimited"
# "Default", "Slo_Mo", "Time_Warp"
game_speed = "Default"
# "Default", "Slow", "Fast", "Super_Fast"
ball_max_speed = "Default"
# "Default", "Cube", "Puck", "Basketball", "Beachball", "Anniversary", "Haunted", "Ekin", "SpookyCube"
ball_type = "Default"
# "Default", "Light", "Heavy", "Super_Light", "Curve_Ball", "Beach_Ball_Curve", "Magnus_FutBall"
ball_weight = "Default"
# "Default", "Small", "Medium", "Large", "Gigantic"
ball_size = "Default"
# "Default", "Low", "LowishBounciness", "High", "Super_High"
ball_bounciness = "Default"
# "Normal_Boost", "Unlimited_Boost", "Slow_Recharge", "Rapid_Recharge", "No_Boost"
boost_amount = "Normal_Boost"
# "No_Rumble", "Default", "Slow", "Civilized", "Destruction_Derby", "Spring_Loaded", "Spikes_Only", "Spike_Rush", "Haunted_Ball_Beam", "Tactical", "BatmanRumble"
rumble = "No_Rumble"
# "One", "OneAndAHalf", "Two", "Five", "Ten"
boost_strength = "One"
# "Default", "Low", "High", "Super_High", "Reverse"
gravity = "Default"
# "Default", "Disabled", "Friendly_Fire", "On_Contact", "On_Contact_FF"
demolish = "Default"
# "Three_Seconds", "Two_Seconds", "One_Second", "Disable_Goal_Reset"
respawn_time = "Three_Seconds"
# "Default", "Eleven_Minutes"
max_time = "Default"
# "Default", "Haunted", "Rugby"
game_event = "Default"
# "Default", "Haunted"
audio = "Default"
