[rlbot]
# use this along with launcher = "custom"
# launcher_arg = "legendary"
# "Steam", "Epic", "Custom", "NoLaunch"
launcher = "steam"
# Should RLBot start the bot processes automatically, or will a separate script start them
auto_start_bots = true

[match]
# What game mode the game should load.
# Accepted values are "Soccer", "Hoops", "Dropshot", "Hockey", "Rumble", "Heatseeker", "Gridiron", "Knockout"
game_mode = "Soccer"
# Which map the game should load into
game_map_upk = "Stadium_P"
# Automatically skip replays after a goal. Also stops match replays from being saved.
skip_replays = false
# Skip the kickoff countdown
start_without_countdown = false
# What should we do if you click run while a match is already in progress?
# "RestartIfDifferent", "Restart", "ContinueAndSpawn"
existing_match_behavior = "Restart"
# Whether debug rendering is enabled
enable_rendering = false
# Whether game state manipulation is enabled
enable_state_setting = true
# Whether replays should be automatically saved
auto_save_replay = false
# Whether to use freeplay instead of an exhibition match
freeplay = false

[mutators]
# "FiveMinutes", "TenMinutes", "TwentyMinutes", "Unlimited"
match_length = "FiveMinutes"
# "Unlimited", "OneGoal", "ThreeGoals", "FiveGoals", "SevenGoals", "TenGoals", "TwentyGoals", "ThirtyGoals", "FortyGoals", "FiftyGoals", "SixtyGoals", "SeventyGoals", "EightyGoals", "NinetyGoals", "HundredGoals"
max_score = "Unlimited"
# "One", "Two", "Four", "Six"
multi_ball = "One"
# "Unlimited", "FiveMaxFirstScore", "FiveMaxRandomTeam"
overtime = "Unlimited"
# "Unlimited", "ThreeGames", "FiveGames", "SevenGames"
series_length = "Unlimited"
# "Default", "SloMo", "TimeWarp"
game_speed = "Default"
# "Default", "Slow", "Fast", "SuperFast"
ball_max_speed = "Default"
# "Default", "Cube", "Puck", "Basketball", "Beachball", "Anniversary", "Haunted", "Ekin", "SpookyCube", "Egg", "PlayerSeeking", "Dropshot", "ScoreAbsorb"
ball_type = "Default"
# "Default", "Light", "Heavy", "SuperLight", "CurveBall", "BeachBallCurve", "MagnusFutBall"
ball_weight = "Default"
# "Default", "Small", "Medium", "Large", "Gigantic"
ball_size = "Default"
# "Default", "Low", "Lowish", "High", "SuperHigh"
ball_bounciness = "Default"
# "NormalBoost", "UnlimitedBoost", "SlowRecharge", "RapidRecharge", "NoBoost"
boost_amount = "NormalBoost"
# "Off", "Default", "Slow", "Civilized", "DestructionDerby", "SpringLoaded", "SpikesOnly", "SpikeRush", "HauntedBallBeam", "Tactical", "BatmanRumble", "GrapplingOnly", "HaymakerOnly"
rumble = "Off"
# "One", "OneAndAHalf", "Two", "Five", "Ten"
boost_strength = "One"
# "Default", "Low", "High", "SuperHigh", "Reverse"
gravity = "Default"
# "Default", "Disabled", "FriendlyFire", "OnContact", "OnContactFF", "OnContactFF", "OnBallContact", or "OnBallContactFF"
demolish = "Default"
# "Three_Seconds", "TwoSeconds", "OneSecond", "DisableGoalReset"
respawn_time = "ThreeSeconds"
# "Unlimited", "ElevenMinutes"
max_time = "Unlimited"
# "Default", "Haunted", "Rugby"
game_event = "Default"
# "Default", "Haunted"
audio = "Default"
# "Default", "Low", "High", "SuperHigh"
ball_gravity = "Default"
# "Off", "Territory"
territory = "Off"
# "Unlimited", "ThirtySeconds"
stale_ball = "Unlimited"
# "Default", "Grounded", "Two", "Three", "Four", "Unlimited", "NoJumps"
jump = "Default"
# "OnePointTwentyFiveSeconds", "TwoSeconds", "ThreeSeconds", "Unlimited"
dodge_timer = "OnePointTwentyFiveSeconds"
# "Off", "OneSecond", "TwoSeconds", "ThreeSeconds"
possession_score = "Off"
# "Zero", "One", "Two", "Three"
demolish_score = "Zero"
# "One", "Zero", "Two", "Three", "Five", "Ten"
normal_goal_score = "One"
# "One", "Zero", "Two", "Three", "Five", "Ten"
aerial_goal_score =  "One"
# "Zero", "One", "Two", "Three"
assist_goal_score = "Zero"
# "Default", "Backwards"
input_restriction = "Default"
