[rlbot]
# use this along with launcher = "custom"
# game_path = "legendary"
# "Steam", "Epic", "Custom"
launcher = "steam"
# Should RLBot start the bot processes automatically, or will a separate script start them
auto_start_bots = true

[match]
# What game mode the game should load.
# Accepted values are "Soccer", "Hoops", "Dropshot", "Hockey", "Rumble", "Heatseeker", "Gridiron", "Knockout"
game_mode = "Soccer"
# Which map the game should load into
game_map_upk = "Stadium_P"
# Automatically skip replays after a goal. Also stops match replays from being saved.
skip_replays = false
# Skip the kickoff countdown
start_without_countdown = false
# What should we do if you click run while a match is already in progress?
# "RestartIfDifferent", "Restart", "ContinueAndSpawn"
existing_match_behavior = "Restart"
# Whether debug rendering is enabled
enable_rendering = false
# Whether game state manipulation is enabled
enable_state_setting = false
# Whether replays should be automatically saved
auto_save_replay = false
# Whether to use freeplay instead of an exhibition match
freeplay = false

[mutators]
# "FiveMinutes", "TenMinutes", "TwentyMinutes", "Unlimited"
match_length = "FiveMinutes"
# "Default", "OneGoal", "ThreeGoals", "FiveGoals", "Seven Goals", "Unlimited"
max_score = "Default"
# "One", "Two", "Four", "Six"
multi_ball = "One"
# "Unlimited", "FiveMaxFirstScore", "FiveMaxRandomTeam"
overtime = "Unlimited"
# "Default", "SloMo", "TimeWarp"
game_speed = "Default"
# "Default", "Slow", "Fast", "SuperFast"
ball_max_speed = "Default"
# "Default", "Cube", "Puck", "Basketball", "Beachball", "Anniversary", "Haunted", "Ekin", "SpookyCube"
ball_type = "Default"
# "Default", "Light", "Heavy", "SuperLight", "CurveBall", "BeachBallCurve", "MagnusFutBall"
ball_weight = "Default"
# "Default", "Small", "Medium", "Large", "Gigantic"
ball_size = "Default"
# "Default", "Low", "LowishBounciness", "High", "SuperHigh"
ball_bounciness = "Default"
# "NormalBoost", "UnlimitedBoost", "SlowRecharge", "RapidRecharge", "NoBoost"
boost_amount = "NormalBoost"
# "NoRumble", "Default", "Slow", "Civilized", "DestructionDerby", "SpringLoaded", "SpikesOnly", "SpikeRush", "HauntedBallBeam", "Tactical", "BatmanRumble"
rumble = "NoRumble"
# "One", "OneAndAHalf", "Two", "Five", "Ten"
boost_strength = "One"
# "Default", "Low", "High", "SuperHigh", "Reverse"
gravity = "Default"
# "Default", "Disabled", "FriendlyFire", "OnContact", "OnContactFF"
demolish = "Default"
# "ThreeSeconds", "TwoSeconds", "OneSecond", "DisableGoalReset"
respawn_time = "ThreeSeconds"
# "Default", "ElevenMinutes"
max_time = "Default"
# "Default", "Haunted", "Rugby"
game_event = "Default"
# "Default", "Haunted"
audio = "Default"
