[rlbot]
launcher_preference = "steam"
auto_start_bots = true

[match]
num_participants = 4
game_mode = "Soccer"
game_map_upk = "Stadium_P"
skip_replays = false
start_without_countdown = false
existing_match_behavior = "Restart"
enable_rendering = true
enable_state_setting = true
auto_save_replay = false

[mutators]
match_length = "20 Minutes"
ball_max_speed = "Fast"
ball_type = "Puck"
ball_weight = "Super Light"
ball_size = "Large"
ball_bounciness = "Super High"
boost_amount = "Unlimited"
rumble = "Spikes Only"
boost_strength = "1.5x"
respawn_time = "1 Second"

[[bots]]
# The location of the configuration file for your agent here.
# Only total_num_participants config files will be read!
# Everything needs a config, even players and default bots.
config = "./atba.toml"
# Which team the player should be on:
# team 0 (blue) shoots on positive goal, team 1 (orange) shoots on negative goal
team = 0
# Accepted values are "human", "rlbot", "psyonix"
# If no player is specified you will be spawned in as spectator!
# human - not controlled by the framework
# rlbot - controlled by the framework
# psyonix - default bots (skill level can be changed with participant_bot_skill
type = "rlbot"

[[bots]]
config = "tests/agents/atba/atba.toml"
team = 1
# you don't have to specify type/skill for rlbots

[[bots]]
# you don't need to specify a config for psyonix bots and humans
team = 0
type = "psyonix"
# If participant is a bot and not RLBot controlled, this value will be used to set bot skill.
# 0.0 is Rookie, 0.5 is pro, 1.0 is all-star.  You can set values in-between as well.
skill = 1

[[bots]]
type = "human"
team = 1
